/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.util.List;
import model.DataManager;
import model.Hrdina;
import model.InventarService;
import model.ObjektovySoubor;
import model.KomparatorPolozek;
import model.PolozkaInventare;
import model.Potvora;
/**ZADÁNÍ
 * 
Oddělení datového modelu od prezentační logiky.
Použití alespoň jedné asociace 1:N (agregace) mezi třídami modelu (např. evidence nějakých záznamů).
Požadovaná funkčnost z pohledu uživatele: 
přidání, úprava, smazání a zobrazení záznamu,
vyhledávání a řazení dat, 
ukládání a načítání dat ze souboru (nebo databáze, sítě, XML, ...).
Použití GUI s využitím komponent JTable, JMenuBar a JToolBar při dodržení principů uvedených v první odrážce.
 * */

/**
 *
 * @author Tomáš Nechanický
 */

public class SeminarkaAppOkno extends javax.swing.JFrame {
    private InventarService inventarService = null;
    private DataManager dm = null;
    private final boolean okno = true;
    private model.Hrdina hrdina  = new model.Hrdina(30, 0);
    private model.Potvora potvora= new Potvora(null, 0);
    private PolozkaInventare predmet = new PolozkaInventare();
    private int index = -1;
    
    public SeminarkaAppOkno() {
        initComponents();
        dm = new ObjektovySoubor();
        inventarService = new InventarService(dm);
        zobrazMenu(hrdina);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btVyroba = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        bgSkupina1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taKonzole = new javax.swing.JTextArea();
        btKonec = new javax.swing.JButton();
        btVyprava = new javax.swing.JButton();
        laZivoty = new javax.swing.JLabel();
        laZlato = new javax.swing.JLabel();
        btInventar = new javax.swing.JButton();
        btBoj = new javax.swing.JButton();
        btUtek = new javax.swing.JButton();
        tfNazev = new javax.swing.JTextField();
        laNazev = new javax.swing.JLabel();
        laCena = new javax.swing.JLabel();
        tfCena = new javax.swing.JTextField();
        btVyrobit = new javax.swing.JButton();
        btUlozitData = new javax.swing.JButton();
        btNactiData = new javax.swing.JButton();
        tfVyhledavaciPole = new javax.swing.JTextField();
        btHledejPolozku = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        paEdit = new javax.swing.JPanel();
        laNazevEdit = new javax.swing.JLabel();
        tfNazevEdit = new javax.swing.JTextField();
        laCenaEdit = new javax.swing.JLabel();
        tfCenaEdit = new javax.swing.JTextField();
        btOk = new javax.swing.JButton();
        laEdit = new javax.swing.JLabel();
        tfIndexPolozky = new javax.swing.JTextField();
        btUpravit = new javax.swing.JButton();
        btProdat = new javax.swing.JButton();
        paRazeni = new javax.swing.JPanel();
        laRazeni = new javax.swing.JLabel();
        rbRazeniDleNazvu = new javax.swing.JRadioButton();
        rbRazeniDleCeny = new javax.swing.JRadioButton();

        btVyroba.setText("Vyrobit předmět");

        jButton1.setText("jButton1");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Semestrálka - Nechanický");

        taKonzole.setEditable(false);
        taKonzole.setColumns(20);
        taKonzole.setRows(5);
        jScrollPane1.setViewportView(taKonzole);

        btKonec.setText("Konec");
        btKonec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKonecActionPerformed(evt);
            }
        });

        btVyprava.setText("Výprava");
        btVyprava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVypravaActionPerformed(evt);
            }
        });

        laZivoty.setText("------------");

        laZlato.setText("---------");

        btInventar.setText("Inventář");
        btInventar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInventarActionPerformed(evt);
            }
        });

        btBoj.setText("Boj");
        btBoj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBojActionPerformed(evt);
            }
        });

        btUtek.setText("Útěk");
        btUtek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUtekActionPerformed(evt);
            }
        });

        laNazev.setText("Název");

        laCena.setText("Cena");

        btVyrobit.setText("Vyrobit předmět");
        btVyrobit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVyrobitActionPerformed(evt);
            }
        });

        btUlozitData.setText("Uložit");
        btUlozitData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUlozitDataActionPerformed(evt);
            }
        });

        btNactiData.setText("Načti");
        btNactiData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNactiDataActionPerformed(evt);
            }
        });

        btHledejPolozku.setText("Hledej v Inventáři");
        btHledejPolozku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHledejPolozkuActionPerformed(evt);
            }
        });

        btEdit.setText("Upravit/Prodat předmět");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });

        paEdit.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        laNazevEdit.setText("Název");

        laCenaEdit.setText("Cena");

        btOk.setText("Ok");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        laEdit.setText("Zadej číslo předmětu:");

        btUpravit.setText("Upravit");
        btUpravit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpravitActionPerformed(evt);
            }
        });

        btProdat.setText("Prodat");
        btProdat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProdatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paEditLayout = new javax.swing.GroupLayout(paEdit);
        paEdit.setLayout(paEditLayout);
        paEditLayout.setHorizontalGroup(
            paEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paEditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(laEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfIndexPolozky, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laNazevEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNazevEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laCenaEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCenaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btUpravit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btProdat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paEditLayout.setVerticalGroup(
            paEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paEditLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(paEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(laNazevEdit)
                        .addComponent(tfNazevEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfCenaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(laCenaEdit)
                        .addComponent(btUpravit)
                        .addComponent(btProdat))
                    .addGroup(paEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(laEdit)
                        .addComponent(tfIndexPolozky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btOk)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paRazeni.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        laRazeni.setText("Řazení předmětů v invetáři:");

        bgSkupina1.add(rbRazeniDleNazvu);
        rbRazeniDleNazvu.setSelected(true);
        rbRazeniDleNazvu.setText("dle názvu");
        rbRazeniDleNazvu.setToolTipText("");
        rbRazeniDleNazvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRazeniDleNazvuActionPerformed(evt);
            }
        });

        bgSkupina1.add(rbRazeniDleCeny);
        rbRazeniDleCeny.setText("dle ceny");
        rbRazeniDleCeny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRazeniDleCenyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paRazeniLayout = new javax.swing.GroupLayout(paRazeni);
        paRazeni.setLayout(paRazeniLayout);
        paRazeniLayout.setHorizontalGroup(
            paRazeniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paRazeniLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paRazeniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(paRazeniLayout.createSequentialGroup()
                        .addComponent(rbRazeniDleNazvu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbRazeniDleCeny))
                    .addComponent(laRazeni))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        paRazeniLayout.setVerticalGroup(
            paRazeniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paRazeniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(laRazeni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paRazeniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbRazeniDleNazvu)
                    .addComponent(rbRazeniDleCeny))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(laZivoty)
                        .addGap(18, 18, 18)
                        .addComponent(laZlato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfVyhledavaciPole, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btHledejPolozku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btNactiData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btUlozitData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btKonec))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btInventar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btVyprava)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btBoj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btUtek)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(laNazev)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNazev, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(laCena)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCena, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btVyrobit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btEdit))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(paRazeni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laZivoty, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btKonec)
                    .addComponent(laZlato)
                    .addComponent(btUlozitData)
                    .addComponent(btNactiData)
                    .addComponent(tfVyhledavaciPole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btHledejPolozku))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVyprava)
                    .addComponent(btInventar)
                    .addComponent(btBoj)
                    .addComponent(btUtek)
                    .addComponent(laNazev)
                    .addComponent(tfNazev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laCena)
                    .addComponent(tfCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVyrobit)
                    .addComponent(btEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paRazeni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btKonecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKonecActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btKonecActionPerformed
    private void btInventarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInventarActionPerformed
        index = -1;
        taKonzole.append("\n---------------INVENÁŘ------------------\n");
        if(rbRazeniDleNazvu.isSelected()== true){
            inventarService.serad(KomparatorPolozek.DLE_NAZVU);
        } else if (rbRazeniDleCeny.isSelected() == true){
            inventarService.serad(KomparatorPolozek.DLE_CENY);
        }
        taKonzole.append(inventarService.getPolozkyJakoString(okno));
        
        tfVyhledavaciPole.setVisible(true);
        btHledejPolozku.setVisible(true);
        
        laCena.setVisible(true);
        laNazev.setVisible(true);
        tfCena.setVisible(true);
        tfNazev.setVisible(true);
        btVyrobit.setVisible(true);
        btEdit.setVisible(true);
        
                
        
    }//GEN-LAST:event_btInventarActionPerformed
    private void btVypravaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVypravaActionPerformed
                
                potvora = model.VypravaOkno.vyprava(hrdina);
                    
                    btInventar.setVisible(false);
                    btVyprava.setVisible(false);
                    
                    tfIndexPolozky.setVisible(true);
                    laEdit.setVisible(true);
                    btOk.setVisible(true);
                    paEdit.setVisible(false);
                    btEdit.setVisible(false);

                    laCena.setVisible(false);
                    laNazev.setVisible(false);
                    tfCena.setVisible(false);
                    tfNazev.setVisible(false);
                    btVyrobit.setVisible(false);

                    btUpravit.setVisible(false);
                    btProdat.setVisible(false);
                    laCenaEdit.setVisible(false);
                    tfCenaEdit.setVisible(false);
                    tfNazevEdit.setVisible(false);
                    laNazevEdit.setVisible(false);

                    tfVyhledavaciPole.setVisible(false);
                    btHledejPolozku.setVisible(false);
    }//GEN-LAST:event_btVypravaActionPerformed
    private void btBojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBojActionPerformed
        taKonzole.append("\nRozhodl jsi se bojovat.");
        predmet = model.VypravaOkno.boj(potvora, hrdina);
        if (predmet != null){
            inventarService.pridejPolozku(predmet.getNazev(), predmet.getCena());
            zobrazMenu(hrdina);
        }
    }//GEN-LAST:event_btBojActionPerformed
    private void btUtekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUtekActionPerformed
        boolean utek = false;
        utek = model.VypravaOkno.utek(potvora, hrdina);
        
        if (utek == true){
            utek = false;
            zobrazMenu(hrdina);
        } else {
            model.VypravaOkno.rozhodnuti(potvora, hrdina);
        }
    }//GEN-LAST:event_btUtekActionPerformed
    private void btVyrobitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVyrobitActionPerformed
        String nazev = null;
        double cena = 0;
        
        if (tfNazev.getText().isEmpty()){
            taKonzole.append("\nZadejte název předmětu.");
        } else if (tfCena.getText().isEmpty()){
            taKonzole.append("\nZadejte cenu předmětu.");
        } else if (utils.Vstupy.isDouble(tfCena.getText())== false){
            taKonzole.append("\nZadejte cenu předmětu.[číslo]");
        } else {
            nazev = tfNazev.getText();
            cena = Double.parseDouble(tfCena.getText());
            inventarService.pridejPolozku(nazev, cena);
            taKonzole.append("\nPředmět " + nazev + " v hodnotě: " + cena + " zlatých byl přidán do inventáře.\n");
        
        laCena.setVisible(false);
        laNazev.setVisible(false);
        tfCena.setVisible(false);
        tfNazev.setVisible(false);
        btVyrobit.setVisible(false);
        tfVyhledavaciPole.setVisible(false);
        btHledejPolozku.setVisible(false);
        
        paEdit.setVisible(false);
        btEdit.setVisible(false);
        }
    }//GEN-LAST:event_btVyrobitActionPerformed
    private void btUlozitDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUlozitDataActionPerformed
        ulozData();
    }//GEN-LAST:event_btUlozitDataActionPerformed
    private void btNactiDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNactiDataActionPerformed
        nactiData();
    }//GEN-LAST:event_btNactiDataActionPerformed
    private void btHledejPolozkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHledejPolozkuActionPerformed
        List<PolozkaInventare> v = inventarService.hledej(tfVyhledavaciPole.getText());

        if (v != null) {
            taKonzole.append("\nNALEZENE ZAZNAMY:" + "\n");
                //razeni i v hledanych polozkach inventare
                if(rbRazeniDleNazvu.isSelected()== true){
                    inventarService.serad(KomparatorPolozek.DLE_NAZVU);
                } else if (rbRazeniDleCeny.isSelected() == true){
                    inventarService.serad(KomparatorPolozek.DLE_CENY);
                }
            for (PolozkaInventare pol : v) {
                taKonzole.append(pol.toString() + "\n");
            }
            laCena.setVisible(false);
            laNazev.setVisible(false);
            tfCena.setVisible(false);
            tfNazev.setVisible(false);
            btVyrobit.setVisible(false);
            tfVyhledavaciPole.setVisible(false);
            btHledejPolozku.setVisible(false);
            btEdit.setVisible(false);
        } else {
            taKonzole.append("\nNic nenalezeno!");
        }
    }//GEN-LAST:event_btHledejPolozkuActionPerformed
    private void rbRazeniDleNazvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRazeniDleNazvuActionPerformed
        inventarService.serad(KomparatorPolozek.DLE_NAZVU);
    }//GEN-LAST:event_rbRazeniDleNazvuActionPerformed
    private void rbRazeniDleCenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRazeniDleCenyActionPerformed
        inventarService.serad(KomparatorPolozek.DLE_CENY);
    }//GEN-LAST:event_rbRazeniDleCenyActionPerformed
    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        //if (!inventarService.inventar){
        if (inventarService.pocetPredmetu() > 0){
        taKonzole.append("\n-----------------EDIT-------------------\n");
        if(rbRazeniDleNazvu.isSelected()== true){
            inventarService.serad(KomparatorPolozek.DLE_NAZVU);
        } else if (rbRazeniDleCeny.isSelected() == true){
            inventarService.serad(KomparatorPolozek.DLE_CENY);
        }
        taKonzole.append(inventarService.getPolozkyJakoStringIndexed(okno));
        
        paEdit.setVisible(true);
        laCenaEdit.setVisible(false);
        laNazevEdit.setVisible(false);
        tfCenaEdit.setVisible(false);
        tfNazevEdit.setVisible(false);
        btProdat.setVisible(false);
        btUpravit.setVisible(false);
        btOk.setVisible(true);
        btEdit.setVisible(false);
  
        tfVyhledavaciPole.setVisible(true);
        btHledejPolozku.setVisible(true);
        
        laCena.setVisible(true);
        laNazev.setVisible(true);
        tfCena.setVisible(true);
        tfNazev.setVisible(true);
        btVyrobit.setVisible(true);
        } else taKonzole.append("\nInventář je prázdný\n");
    }//GEN-LAST:event_btEditActionPerformed
    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        int max = inventarService.pocetPredmetu() - 1;
                
        if (tfIndexPolozky.getText().isEmpty()){
            taKonzole.append("\nZadej číslo předmětu");
        } else if (utils.Vstupy.isInt(tfIndexPolozky.getText())== false){
            taKonzole.append("\nNesprávný formát čísla předmětu");
        } else if (Integer.parseInt(tfIndexPolozky.getText()) > max || Integer.parseInt(tfIndexPolozky.getText()) < 0 ){
            taKonzole.append("\nŠpatné číslo předmětu předmětu");
        } else{
            
            PolozkaInventare predmet = new PolozkaInventare();
            index = Integer.parseInt(tfIndexPolozky.getText());
            predmet = inventarService.vyberPolozku(index);
            
            tfCenaEdit.setText(Double.toString(predmet.getCena()));
            tfNazevEdit.setText(predmet.getNazev());
            tfIndexPolozky.setVisible(false);
            laEdit.setVisible(false);
            btOk.setVisible(false);
            
            btUpravit.setVisible(true);
            btProdat.setVisible(true);
            laCenaEdit.setVisible(true);
            tfCenaEdit.setVisible(true);
            tfNazevEdit.setVisible(true);
            laNazevEdit.setVisible(true);
        }
    }//GEN-LAST:event_btOkActionPerformed
    private void btUpravitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpravitActionPerformed
        String nazev = null;
        double cena = 0;
        
        if (tfNazevEdit.getText().isEmpty()){
            taKonzole.append("\nZadejte správný název předmětu.");
        } else if (tfCenaEdit.getText().isEmpty()){
            taKonzole.append("\nZadejte cenu předmětu.");
        } else if (utils.Vstupy.isDouble(tfCenaEdit.getText())== false){
            taKonzole.append("\nZadejte cenu předmětu.[číslo]");
        } else {
            inventarService.odeberPolozku(index);
            nazev = tfNazevEdit.getText();
            cena = Double.parseDouble(tfCenaEdit.getText());
            inventarService.pridejPolozku(nazev, cena);
            taKonzole.append("\nModifikovaný předmět " + nazev + " v hodnotě: " + cena + " zlatých byl přidán do inventáře.\n");
            index = -1;
            
            tfIndexPolozky.setVisible(true);
            laEdit.setVisible(true);
            btOk.setVisible(true);
            paEdit.setVisible(false);
            
            laCena.setVisible(false);
            laNazev.setVisible(false);
            tfCena.setVisible(false);
            tfNazev.setVisible(false);
            btVyrobit.setVisible(false);

            btUpravit.setVisible(false);
            btProdat.setVisible(false);
            laCenaEdit.setVisible(false);
            tfCenaEdit.setVisible(false);
            tfNazevEdit.setVisible(false);
            laNazevEdit.setVisible(false);
            
            tfVyhledavaciPole.setVisible(false);
            btHledejPolozku.setVisible(false);
        }
    }//GEN-LAST:event_btUpravitActionPerformed

    private void btProdatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProdatActionPerformed
        predmet = inventarService.vyberPolozku(index);
        
        taKonzole.append("\nPředmět " + predmet.getNazev() + " v hodnotě: " + predmet.getCena() + " zlatých byl prodán.\n");
        int cena = (int)(predmet.getCena() + 0.5d);
        hrdina.setZlato(hrdina.getZlato() + cena);
        laZlato.setText("Zlato: " + hrdina.getZlato());
        inventarService.odeberPolozku(index);
        index = -1;
        
        tfIndexPolozky.setVisible(true);
            laEdit.setVisible(true);
            btOk.setVisible(true);
            paEdit.setVisible(false);
            
            laCena.setVisible(false);
            laNazev.setVisible(false);
            tfCena.setVisible(false);
            tfNazev.setVisible(false);
            btVyrobit.setVisible(false);

            btUpravit.setVisible(false);
            btProdat.setVisible(false);
            laCenaEdit.setVisible(false);
            tfCenaEdit.setVisible(false);
            tfNazevEdit.setVisible(false);
            laNazevEdit.setVisible(false);
            
            tfVyhledavaciPole.setVisible(false);
            btHledejPolozku.setVisible(false);
    }//GEN-LAST:event_btProdatActionPerformed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeminarkaAppOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeminarkaAppOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeminarkaAppOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeminarkaAppOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeminarkaAppOkno().setVisible(true);
            }
        });
    }
    public void zobrazMenu(Hrdina hrdina){
        index = -1;
        btInventar.setVisible(true);
        btVyprava.setVisible(true);
        
        laCena.setVisible(false);
        laNazev.setVisible(false);
        tfCena.setVisible(false);
        tfNazev.setVisible(false);
        btVyrobit.setVisible(false);
        btEdit.setVisible(false);
        paEdit.setVisible(false);
        
        btUpravit.setVisible(false);
        btProdat.setVisible(false);
        laCenaEdit.setVisible(false);
        tfCenaEdit.setVisible(false);
        tfNazevEdit.setVisible(false);
        laNazevEdit.setVisible(false);
        
        tfVyhledavaciPole.setVisible(false);
        btHledejPolozku.setVisible(false);
        
        btBoj.setVisible(false);
        btUtek.setVisible(false);
        
        taKonzole.append("--------- Vítej v menu hrdino --------\n");
        laZivoty.setText("Životy: " + hrdina.getZivoty());
        laZlato.setText("Zlato: " + hrdina.getZlato());
        taKonzole.append("--------------------------------------------\n");
        taKonzole.append(" - Zobrazení inventaře\n");
        taKonzole.append(" - Jít na místní tržiště\n");
        taKonzole.append(" - Dobrodružná výprava\n");
        taKonzole.append(" - Konec\n\n");
        taKonzole.append("Co uděláš?\n");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSkupina1;
    public static javax.swing.JButton btBoj;
    private javax.swing.JButton btEdit;
    public static javax.swing.JButton btHledejPolozku;
    public static javax.swing.JButton btInventar;
    private javax.swing.JButton btKonec;
    public static javax.swing.JButton btNactiData;
    private javax.swing.JButton btOk;
    private javax.swing.JButton btProdat;
    public static javax.swing.JButton btUlozitData;
    private javax.swing.JButton btUpravit;
    public static javax.swing.JButton btUtek;
    public static javax.swing.JButton btVyprava;
    private javax.swing.JButton btVyroba;
    public static javax.swing.JButton btVyrobit;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    public static javax.swing.JLabel laCena;
    public static javax.swing.JLabel laCenaEdit;
    private javax.swing.JLabel laEdit;
    public static javax.swing.JLabel laNazev;
    public static javax.swing.JLabel laNazevEdit;
    private javax.swing.JLabel laRazeni;
    public static javax.swing.JLabel laZivoty;
    public static javax.swing.JLabel laZlato;
    private javax.swing.JPanel paEdit;
    private javax.swing.JPanel paRazeni;
    private javax.swing.JRadioButton rbRazeniDleCeny;
    private javax.swing.JRadioButton rbRazeniDleNazvu;
    public static javax.swing.JTextArea taKonzole;
    public static javax.swing.JTextField tfCena;
    public static javax.swing.JTextField tfCenaEdit;
    private javax.swing.JTextField tfIndexPolozky;
    public static javax.swing.JTextField tfNazev;
    public static javax.swing.JTextField tfNazevEdit;
    public static javax.swing.JTextField tfVyhledavaciPole;
    // End of variables declaration//GEN-END:variables
    public void ulozData(){
        try {
            inventarService.uloz();
            taKonzole.append("\nData uložena\n");
            } catch (Exception e) {
            taKonzole.append("\nChyba pri ukládání dat: " + e.getMessage());
        }
    }
    public void nactiData(){
        try {
            inventarService.nacti();
            taKonzole.append("\nData načtena\n");
            } catch (Exception e) {
            taKonzole.append("\nChyba při načítání dat: " + e.getMessage());
        }
    }
}
